theme: jekyll-theme-cayman
title: AppWorks PHP Framework
description: A different Approach
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
#      layout: "cayman"
